### ISSUE TITLE
Listen to Error State in Widgets

### ISSUE THREAD

**Issue by Hamza-ye** [MassPro-NMCPYE/data-run-mobile#5]
Use `Consumer` or `ConsumerWidget` to listen for changes in the error state and react accordingly in the UI.

**Tasks:**
- [ ] Identify key widgets that need to respond to error state changes.
- [ ] Implement `Consumer` or `ConsumerWidget` to listen to `errorHandlerProvider`.
- [ ] Display error messages to users when appropriate.
